### ISSUE TITLE
  怎么编译出assemble和运行这个文件啊

### ISSUE THREAD

**Issue by JerryLiew** [archeryue/cpc#1]

**Comment by archeryue** [comment]
assemble 文件是我输出出来 debug 分析用的，不能直接运行。
"./cpc hello.c" 就可以直接编译+运行 hello.c 的代码了。

**Comment by archeryue** [comment]
验证自举的话，“./cpc cpc.c hello.c”，这样就会编译和运行 cpc.c，并且会把 hello.c 当做 cpc.c 的参数。
