### ISSUE TITLE
[Question]About open() don't work

### ISSUE THREAD

**Issue by Yousazoe** [archeryue/cpc#2]
你好，看了你的视频学到了很多。在动手写虚拟机部分的时候不知为何 `open()` 似乎无法正常工作，我主要的参考代码来源于 https://lotabout.me/2015/write-a-C-interpreter-2/，在 MacOS Clion 上始终显示 could not open(null)，我尝试替换64位、更换为 Linux 系统以及改变代码结构，但并没有效果，现在我不知道如何解决，希望您能够帮助我。

我的代码可以通过1s浏览器上浏览：https://github1s.com/Yousazoe/CmmCompiler/blob/HEAD/main.c

**Comment by archeryue** [comment]
从你代码中输出的log来看，你传入的参数有些问题，你可以检查下。由于你参考的代码不是我写的，也可以尝试联系下你参考的原作者，看看是不是他程序的调用方式与你想的不同？

**Comment by archeryue** [comment]
由于这个issue不是涉及cpc项目本身的问题，我就先关掉哈
